### ISSUE TITLE
Rupee and bombs logic

### ISSUE THREAD

**Issue by Vivelin** [Vivelin/SMZ3Randomizer#156]
Assuming we can read the current rupee count, we could show whether Zora and other places are in logic depending on actual rupee count rather than simply randomizer rupees.

We could possibly do the same for Zelda bombs and maybe even for missiles in Super Metroid?

**Comment by MattEqualsCoder** [comment]
I'm a bit divided about this. Perhaps it could be a different color/icon on the map and have some way to designate them in the location list they could possibly work, but we'd need to make sure that the meaning is pretty obvious.

For Zora, the logic of the randomizer still wouldn't expect you to go there even if you get money from somewhere else, and I'm not sure the tracker should show something as in logic when it's not. I think it could mislead players into going there thinking it's the next part of the chain when it's not.

I have the opposite concern when it comes to bombs/missiles. I'd worry about people thinking something is out of logic because of it not showing up but all they need to do is find a missile from an enemy drop or find a bomb in a bush.
