### ISSUE TITLE
Allow Custom Toggle Go Mode Voice Prompt

### ISSUE THREAD

**Issue by MattEqualsCoder** [Vivelin/SMZ3Randomizer#309]
So generally it would be kind of a paint to allow people to edit custom voice detection prompts because lots of things like items are strung together via multiple sets of things you can possibly say. For example for item tracking we have this:

```
var trackItemNormal = new GrammarBuilder()
                .Append("Hey tracker,")
                .Optional("please", "would you kindly")
                .OneOf("track", "add")
                .Append(ItemNameKey, itemNames);
```

However, I think we could probably do this for toggling go mode on since it's a pretty basic command. Pink kind of wanted to this for saying "Hey tracker, it's pizza time."

**Comment by Vivelin** [comment]
It'd be a pretty big undertaking to overhaul the voice recognition grammar system but I can imagine that's something people would want to do. If it'll be more than just this, I'd say we could make that work somehow.

But that's probably more easily done once I've finally gotten a chance to implement voice commands as their own class rather than just loose unstructured methods on Tracker.cs.

**Comment by MattEqualsCoder** [comment]
I haven't heard of much rumblings of people would want to change the voice recognition grammar too much, so personally I don't think we need to redo the whole grammar system. I just don't see many people changing how they ask tracker to mark a location or anything like that. The closest we've gotten is Pink asking for this and for "get a load of this" for the map, and that's generic enough it was fine adding in to the base code.

I could definitely see go mode being something people might want to change as I can see folks using their own catch phrase or something for it. So I think just having a one off list of possible go mode phrases in the responses config would probably suffice.
