### ISSUE TITLE
Better keysanity support in Tracker

### ISSUE THREAD

**Issue by Vivelin** [Vivelin/SMZ3Randomizer#33]
It's already possible to track small and big keys, and technically possible to add them to the tracker layout without a code change. This is far from ideal, however.

- A better space-optimized layout for keys might be necessary;
- Separate "playing/tracking logic" from "randomizer logic";
  - The logic only accounts for randomized keys found in chests, not other keys that people playing would probably track;
  - Also makes sense for things like the green pendant and defeating Agahnim.
- Keys in _A Link to the Past_ are straightforward enough. Keycards in Super Metroid, however, were hacked in, and make little sense to most people. 
  - Once a keycard has been tracked, newly unlocked locations should show up on the map. That will already help, but...
  - ...it would be nice to figure out a way to visualize the keycards on the various Super Metroid maps.

**Comment by MattEqualsCoder** [comment]
So, I might start working on this soon as part of my plans on allowing the split keysanity. But, I think we may need an overhaul on the tracker window to best do this.

1. Currently the tracker window is currently managed via a combination of hard coding and the items portion of tracker.json. I think we should maybe move the tracker layout to a separate config so that we can have multiple layouts easier. This could offer the possibility of multiple layouts in the future or allow people to make their own.
2. We may need something along the lines of a "TrackerItemType" enum which would be used to connect between configs. These would be things like "Content", "Death", "GameItem" (this would be used for ones that need to use the InternalItemType to map to ItemType), etc. This would solve part of the problems ran into in https://github.com/Vivelin/SMZ3Randomizer/issues/60

**Comment by Vivelin** [comment]
1. I do want to support multiple separate configs that can be joined, but moving this out into its own config is probably for the best. 

2. This is difficult... I don't know if an enum is the best solution for this. I want people to be able to add custom nonsense without having to touch the code for it, so an enum wouldn't work. But just plain integers aren't exactly intuitive, either... I'm not sure what's good, here.

**Comment by MattEqualsCoder** [comment]
Yeah, I think in general we may just need to introduce a "key" field and just tell people to be careful with that field in particular.
