### ISSUE TITLE
In Keysanity, it would be useful to tell Tracker to mark unknown key, map, etc.

### ISSUE THREAD

**Issue by CPColin** [Vivelin/SMZ3Randomizer#358]
I noticed while playing Keysanity yesterday and while watching PKR play Keysanity today that it would be helpful to be able to tell Tracker that "a key", "a map", "a big key", or "a compass" is at a visible location like Lumberjack Cave or Spectacle Rock. Currently, I think she only marks it if you say the actual dungeon name, which you don't know yet.

If we end up allowing Tracker to mark things when the player uses a generic term for them, we could extend this to marking "a bottle" when the player sees a bottle with something in it.

**Comment by MattEqualsCoder** [comment]
Huh. I'm actually a bit surprised it doesn't already work because I thought I've seen generic small keys, boss keys, etc. in the item types. But maybe we don't have them specified in the configs they won't work.

That being said, even if we were to add them to the configs, we'd probably need to do something to avoid tracker complaining about it being something else.

**Comment by Vivelin** [comment]
This goes for bottles, too.

**Comment by CPColin** [comment]
It's possible they're in there, but neither Pink nor I knew the right phrasing. I'll take a peek tomorrow.

**Comment by CPColin** [comment]
Okay, yeah, `ItemType` does have values for generic keys, etc., but since they're not in the item pool, Tracker doesn't listen for them.
